/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iflytek_tts_TtsService_Tts */

#ifndef _Included_com_iflytek_tts_TtsService_Tts
#define _Included_com_iflytek_tts_TtsService_Tts
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iflytek_tts_TtsService_Tts
 * Method:    ivTTS_init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iflytek_tts_TtsService_Tts_ivTTS_1init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iflytek_tts_TtsService_Tts
 * Method:    ivTTS_cleanup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_tts_TtsService_Tts_ivTTS_1cleanup
  (JNIEnv *, jclass);

/*
 * Class:     com_iflytek_tts_TtsService_Tts
 * Method:    ivTTS_reInit
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iflytek_tts_TtsService_Tts_ivTTS_1reInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iflytek_tts_TtsService_Tts
 * Method:    ivTTS_speak
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_tts_TtsService_Tts_ivTTS_1speak
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iflytek_tts_TtsService_Tts
 * Method:    ivTTS_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iflytek_tts_TtsService_Tts_ivTTS_1stop
  (JNIEnv *, jclass);

/*
 * Class:     com_iflytek_tts_TtsService_Tts
 * Method:    ivTTS_setParameter
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_tts_TtsService_Tts_ivTTS_1setParameter
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_iflytek_tts_TtsService_Tts
 * Method:    ivTTS_getParameter
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_iflytek_tts_TtsService_Tts_ivTTS_1getParameter
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
